# Generated by Django 4.2.19 on 2026-04-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comtrade_code', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('iso_alpha2', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='HSProduct',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_label', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorldExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('value_usd_thousands', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='loadFiles_w_year_36beee_idx')],
                'unique_together': {('product_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PartnerImportFromWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('value_usd_thousands', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['partner', 'year'], name='loadFiles_p_partner_dfe721_idx')],
                'unique_together': {('partner', 'product_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CountryExportToWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('value_usd_thousands', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['reporter', 'year'], name='loadFiles_c_reporte_6b8257_idx')],
                'unique_together': {('reporter', 'product_code', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CountryExportToPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('value_usd_thousands', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['partner', 'reporter'], name='loadFiles_c_partner_808ca9_idx')],
                'unique_together': {('reporter', 'partner', 'product_code', 'year')},
            },
        ),
    ]
