# Generated by Django 4.2.19 on 2026-05-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadFiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSSITCConcordance',
            fields=[
                ('product_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sitc_code', models.CharField(max_length=10)),
                ('sitc_section', models.CharField(max_length=1)),
            ],
            options={
                'indexes': [models.Index(fields=['sitc_section'], name='loadFiles_h_sitc_se_8657a5_idx')],
            },
        ),
    ]
